### ISSUE TITLE
Checklist for DTU projects that need to be dockerized:

### ISSUE THREAD

**Issue by viktorsmari** [dtulibrary/mother-docker#1]
Check of the services that have been containerized:
- [x] Toshokan (Findit)
- [x] FinditAuth (riyosha)
- [x] DocDel (haitatsu)
- [x] Getit (kyandi) - not a rails app? Need to know ruby version 1.9.3-p194 ?
- [x] Sendit (tsushin) - almost working (fix redirect), needs a config for auth,
- [x] DocumentStore (bunsho)
- [x] Redmine (maybe as close to 2.5.1 as possible - dunno)
- [x] Cover images (gazo)
- [ ] Mock payment service (DIBS)
- [x] Alerting (keikoku)
- [ ] CAS casify
